# Generated by Django 5.2.6 on 2025-11-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CAS', 'Casa'), ('DEP', 'Departamento'), ('TER', 'Terreno')], max_length=3),
        ),
    ]
