# Generated by Django 5.2.6 on 2025-10-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='autohr',
            new_name='author',
        ),
    ]
