# Generated by Django 5.2.6 on 2025-10-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0002_rename_autohr_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='propic',
            field=models.ImageField(blank=True, default='def_user.png', upload_to=''),
        ),
    ]
