# Generated by Django 5.2.6 on 2025-11-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0003_person_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='propic',
            field=models.ImageField(default='def_user.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
