# Generated by Django 5.2.6 on 2025-11-12 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('board', models.JSONField(default=list)),
                ('current_player', models.CharField(choices=[('1', 'juagador 1'), ('2', 'el otro 2')], default='1', max_length=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('tie', 'Tie')], default='active', max_length=10)),
                ('winner', models.CharField(blank=True, choices=[('1', 'juagador 1'), ('2', 'el otro 2')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
