# Generated by Django 5.2.6 on 2025-12-01 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='active_player',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player1_games', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WIN_P1', 'Player 1 won'), ('WIN_P2', 'Player 2 won'), ('TIE', 'Tie')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(default='_________', max_length=9),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='room_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
